language: vim

before_script: |
  # git clone https://github.com/tpope/vim-sensible.git sensible

  git clone https://github.com/vim/vim
  cd vim
  # ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp
  ./configure --with-features=huge
  make -j4
  sudo make install
  cd -

script: |
  /usr/local/bin/vim --version
  cd tests
  TESTS="`ls *.vim | tr "\n" ' '`"
  # UT doesn't exit vim and doesn't provide error codes. Not sure if it's
  # easier to switch to vader or add this functionality to UT. For now, just
  # quit which should always "pass" tests. At least we'll have the output.
  /usr/local/bin/vim -Nu vimrc_test -c ":UTRun $TESTS" -c "quit" > /dev/null
