language: ruby
cache: bundler
sudo: false
addons:
  apt:
    packages:
      - vim-gtk
rvm:
  - 2.1.5 # vim-flavor requires a recent version of ruby
script: bundle exec rake ci
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
